### ISSUE TITLE
IP address is not saved

### ISSUE THREAD

**Issue by StefanKert** [NickCraver/StackExchange.Exceptional#101]
As @nickalbrecht mentioned in #85 there is an issue with resolving the remote ip in the current alpha. 

![image](https://user-images.githubusercontent.com/7176615/29551848-08409452-8715-11e7-99e1-8019657973e8.png)

The Ip is always set to the default value 0.0.0.0. This is because of the new implementation for retrieving the Ip

https://github.com/NickCraver/StackExchange.Exceptional/blob/c4217546a80d15fb6cd6eae4e50e1b70e37364d1/src/StackExchange.Exceptional.Shared/Settings.cs#L61-L65

Basically, @NickCraver introduced this setting for getting the current IP address. This is then used in the `Error` class and since this setting is always null the ip address has no value in first place. When calling the Errors property `IPAddress` it is then loaded from `ServerVariables` which is not a real obvious behavior.

```
        public string IPAddress
        {
            get => _ipAddress ?? (_ipAddress = ServerVariables?.GetRemoteIP() ?? "");
            set => _ipAddress = value;
        }
```
So the first improvement that could be made, since the IPAddress is always logged, is to change the SetIPAddress method so that it directly calls `GetRemoteIP` if no Func is set. 

Also this problem only exists in AspNetCore because the `REMOTE_ADDR` is never added to `ServerVariables`. If we add the the remote ip address we are able to save the ip address again.

```csharp
  { "REMOTE_ADDR", context.Connection.RemoteIpAddress.ToString() }
```

![image](https://user-images.githubusercontent.com/7176615/29554554-e3ddb9ea-871f-11e7-908c-930f01c3c28e.png)

**Comment by NickCraver** [comment]
Fixed in the commit above, but I'm not happy with the workaround and limitations to getting an IP. The settings split issue is the same as before (with `GetCustomData`), and will need more global love to make this more flexible and usable.
