### ISSUE TITLE
NuGet package Not working with Asp.net core

### ISSUE THREAD

**Issue by AhmedRagheb** [NickCraver/StackExchange.Exceptional#114]
I've installed the NuGet package in my DotNetCore 2.0 project and setup the SQL store and nothing logged in Db
[Install-Package StackExchange.Exceptional.AspNetCore -Version 2.0.0-alpha2-00171](url)

I've downloaded the DotNetCore Sample and remove project reference and replaced with NuGet package and also nothing logged in Db.

**Comment by NickCraver** [comment]
@AhmedRagheb Did you setup the DB by creating the schema? Instructions here: https://nickcraver.com/StackExchange.Exceptional/Providers/SqlServer

If you have the route added to see the error log (as in the sample application), you can see why it's not logging.

**Comment by AhmedRagheb** [comment]
@NickCraver Thanks for your reply.
Yes, I did.
If I download your sample project, everything will work fine. but if I remove the reference project and replaced with the NuGet package, it will not log. So, the issue not in my SQL setup, the problem in NuGet package (I think).

**Comment by zbecknell** [comment]
I'm reproducing this using the latest MyGet package (alpha3-00183).  I just added it and am setting up Exceptional like so:

In `ConfigureServices`:

```csharp
services.AddExceptional(settings =>
{
    settings.SetDefaultStore(new SQLErrorStore(new ErrorStoreSettings
    {
        ApplicationName = "App Name",
        Type = "SQL",
        ConnectionString = Configuration.GetConnectionString("DefaultConnection")
    }));
});
```

In `Configure`:

```csharp
app.UseExceptional();
```

I do have the table created.  Trying to get to the bottom of it now.

**Comment by zbecknell** [comment]
Ok, I found my problem.  My request pipeline was ordered incorrectly.  I had this:

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseExceptional();

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseBrowserLink();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
    }
```

And the DeveloperExceptionPage was terminating the pipeline before the exception reached Exceptional to log.  Moving `app.UseExceptional()` after the DeveloperExceptionPage enabled the logging.

**Comment by NickCraver** [comment]
@AhmedRagheb The problem was (I'm fairly sure) NuGet just didn't have a recent build. If you try latest from NuGet it should work fine :)
