### ISSUE TITLE
Missing  app.UseExceptional(...) overloads

### ISSUE THREAD

**Issue by xps** [NickCraver/StackExchange.Exceptional#120]
Following the documentation at https://nickcraver.com/StackExchange.Exceptional/AspDotNetCore, I am trying to pass settings to `app.UseExceptional(...)`, but there is only one overload of that method, and it doesn't take any argument (see the [ExceptionalBuilderExtensions](https://github.com/NickCraver/StackExchange.Exceptional/blob/b54baae48e01abd0daf8d10dda0e0d26df092082/src/StackExchange.Exceptional.AspNetCore/ExceptionalBuilderExtensions.cs) file).

How can I configure it, especially the exception storage?

PS: using the latest 2.x branch on ASP.NET Core

Thanks

**Comment by xps** [comment]
I'll answer my own question: the configuration is now passed to the `.AddExceptional(...)` method, instead of `.UseExceptional(...)`. 

Would you like me to submit a PR to update the documentation?

**Comment by nickalbrecht** [comment]
`AddExceptional()` is for adding the options/settings that Exceptional needs to the services collection for use with dependency injection. `UseExceptional()` is for setting up the middleware for actually handling the errors. This naming convention is very common with ASPNET Core. You will most likely need both in your app to take full advantage of Exceptional.

**Comment by NickCraver** [comment]
@xps absolutely I'd love a PR since you noticed this, time is very thing and all help is tremendously appreciated.

**Comment by mmillican** [comment]
A PR is on the way for this.

**Comment by NickCraver** [comment]
Fixed via #123 :)
