### ISSUE TITLE
postgresql store : what's the type I must use ?

### ISSUE THREAD

**Issue by oooolivierrrr** [NickCraver/StackExchange.Exceptional#151]
I've installed those packages :
StackExchange.Exceptional.AspNetCore 2.0.0-rc2.28
StackExchange.Exceptional.PostgreSql 2.0.0-rc2.28

In configureServices, I have :
```
            services.AddExceptional(Configuration.GetSection("Exceptional"), settings =>
            {
                settings.UseExceptionalPageOnThrow = HostingEnvironment.IsDevelopment();
            });
```
In Configure, the first line is :
`            app.UseExceptional();`
The appSettings :
```
  "Exceptional": {
    "Store": {
      "ApplicationName": "",
      "Type": "PostgreSql",
      "ConnectionString": ""
    }
```

When I try to access the errors action, I get 
```
System.Exception: Could not find error store type: PostgreSql
   at StackExchange.Exceptional.ErrorStore.Get(ErrorStoreSettings settings)
   at StackExchange.Exceptional.Internal.ExceptionalSettingsBase.get_DefaultStore()
   at StackExchange.Exceptional.ExceptionalMiddleware.HandleRequestAsync(HttpContext context)
   at api.Controllers.DefaultController.Exceptions() 
```

**Comment by NickCraver** [comment]
Can you share what your `.csproj` looks like?

**Comment by NickCraver** [comment]
@oooolivierrrr any update? Also consider the fix in #160 - I believe that workaround is the same issue as here that changes in later versions of ASP.NET Core.

**Comment by oooolivierrrr** [comment]
i gave up

________________________________

**Comment by NickCraver** [comment]
@oooolivierrrr Got it - thanks for responding :)
