### ISSUE TITLE
How to add in .NET Core console app?

### ISSUE THREAD

**Issue by VoidMonk** [NickCraver/StackExchange.Exceptional#174]
Hi, the docs[1] list the required package and steps for using Exceptional in .NET Framework console apps, but I couldn't find anything on how to do the same in .NET Core console app.

Any tips will be great!

[1] https://nickcraver.com/StackExchange.Exceptional/ConsoleDotNet

**Comment by NickCraver** [comment]
Good question! Such an example is long overdue - I'm adding it in #175 right now, docs will be up shortly for .NET Core console goodness :)

**Comment by NickCraver** [comment]
Docs are now up! I added info and a sample application, at https://nickcraver.com/StackExchange.Exceptional/ConsoleDotNetCore :)

**Comment by MattJeanes** [comment]
@NickCraver the page title appears to be incorrect but other than that nice one! I remember having to guess my way around it when I was setting up NET Core console apps ☺

**Comment by NickCraver** [comment]
Doh! Good catch (and thanks!) - fixed up just now :)
