### ISSUE TITLE
How can we log 404, 401, 403 status code type error in Database using StackExchange.Exceptional?

### ISSUE THREAD

**Issue by anomepani** [NickCraver/StackExchange.Exceptional#184]
How can we log 404, 401, 403 status code type error in Database using StackExchange.Exceptional?

In Elmah I have seen that it will log 404 error.
Just wanted to know that if possible using `StackExchange.Exceptional` package then it is very helpful.

**Comment by NickCraver** [comment]
Is the ask here to log the 404 you're getting as a _client_ or a server hosting and serving a 404? If the latter, is this in ASP.NET Core?
