### ISSUE TITLE
Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by dgaspar** [NickCraver/StackExchange.Exceptional#193]
Any chance `StackExchange.Exceptional` could start relying on `Microsoft.Data.SqlClient` instead of `System.Data.SqlClient`?

https://github.com/NickCraver/StackExchange.Exceptional/blob/a3e787a08f21859c653c6c609059334b4e8eeac3/src/StackExchange.Exceptional.Shared/Stores/SQLErrorStore.cs#L4

This seems to be the last line preventing my system from getting rid of the old `System` one. :)

**Comment by NickCraver** [comment]
As of 3.0.1 (headed to NuGet now), `net8.0` will use `Microsoft.Data.SqlClient` instead, and `net462` will remain on `System.Data.SqlClient` for the easiest transition for most teams between as they move to .NET Core.
