### ISSUE TITLE
Is NuGet abandonned?

### ISSUE THREAD

**Issue by Sacha-K** [NickCraver/StackExchange.Exceptional#194]
The last versions are 2.1.0 on NuGet and 2.2.4 on MyGet. Is this intended?

**Comment by pkanavos** [comment]
The landing page explains that MyGet contains CI builds. The download counts in MyGet (2 only for v2.2.4) show that it's not widely used

**Comment by Sacha-K** [comment]
With the NuGet naming convention 2.2.4 is a stable version, the commit message from 2020/03/26 says "Bump to 2.2.x for release", and Opserver has a dependency the 2.2.4 version.

**Comment by NickCraver** [comment]
Not abandoned, just been really busy - pushing 2.2.17 up to NuGet now, I'll close this out once it finishes promoting :)

**Comment by NickCraver** [comment]
NuGets, tags, and release notes updated - thanks for the poke!
