### ISSUE TITLE
Update docs to reference new Settings.Current location

### ISSUE THREAD

**Issue by lookatmike** [NickCraver/StackExchange.Exceptional#206]
It looks like at some point `Settings.Current` moved to `Exceptional.Settings`, but the docs still reference the former. 

Happy to file a PR for this if one would be welcome.

Thanks!

**Comment by NickCraver** [comment]
Just catching up here (sorry time is split across many projects). A PR would be very welcome!

**Comment by NickCraver** [comment]
Fixed in #218, thanks for the poke!

**Comment by lookatmike** [comment]
Hi, my apologies, I completely lost track of this one -- thank you very much for the update.
