### ISSUE TITLE
Request - Ability to Mask or Exclude Sensitive Form Values from Logging and Emails

### ISSUE THREAD

**Issue by ctorx** [NickCraver/StackExchange.Exceptional#208]
**Issue:**
There is currently no way to mask or exclude sensitive form field data from logs or emails.  Form fields such as password, credit card info, etc., are logged and included in emails in plan text. 

**Steps to Reproduce:**
Log an exception from a form post.  Note all form fields and values in plain text are written to FullJson data column as well as displayed in email messages. 

**Recommended Resolution:**
Implement a setting that contains a collection of keys that should be masked or excluded.  When data is written/emailed, mask the value or do not include them at all.  It would be useful to allow the option to specify whether an individual field is masked or excluded.  While not common, one could use sensitive data in the form field key, and in such cases it you would want to exclude it completely instead of masking it's value.

**Comment by NickCraver** [comment]
This is all supported and in the Sample apps - I'm not sure if you're using code or config file style but either way - look for `LogFilters` in any oof the config areas of the examples here: https://github.com/NickCraver/StackExchange.Exceptional/tree/main/samples

It's also in the docs here: https://nickcraver.com/StackExchange.Exceptional/Settings (though the docs don't have the more recent `Header` and `QueryString` - I'll fix that up!).

**Comment by NickCraver** [comment]
Just pushed the docs additions, should be there in a bit.
