### ISSUE TITLE
Grouped exceptions should use the latest/most recent date

### ISSUE THREAD

**Issue by cottsak** [NickCraver/StackExchange.Exceptional#31]
Correct me if I'm wrong, but it seems that when exceptions are grouped, the date (for ordering the item in the list) is taken from the first occurrence of the grouped exception. This seems odd to me and I find myself getting frustrated when I trigger an exception (manually for example), and find that it's not at the top of the list, but rather a few lines down but now with a (2).

I would have thought that like a grouped email thread, that when a new message (or exception) is added to the thread/group, that then the whole group would then be considered new/recent and move to the top of the list.

Is it by design that the last/most recent item in a group is not the one whose date is used for sorting?

**Comment by NickCraver** [comment]
This will be going into 2.0. I'm hoping to get a 2.0 (CoreCLR compatible) version out in the next month or two.

**Comment by cottsak** [comment]
Nice

**Comment by NickCraver** [comment]
Added in V2! There will be schema changes to accommodate this (we need a new column), but it's for the greater good. The scripts are now idempotent for setting up and upgrading to the latest version though.

**Comment by cottsak** [comment]
Available in .NET 4.5?

**Comment by NickCraver** [comment]
Yep v2 should support `net45` and `netstandard2.0`
