### ISSUE TITLE
Missing tagged versions

### ISSUE THREAD

**Issue by mansandersson** [NickCraver/StackExchange.Exceptional#51]
The version numbers used on the nuget packages are not tagged in the git repository. This makes it hard to debug my usage of the library and to see whether a fix for an issue has already been added.

So all in all, adding tags when new versions are released would be really nice.

**Comment by NickCraver** [comment]
Thanks, I'll keep this in mind for upcoming updates. I'll need to refactor several things that make Exceptional's compact design not .Net v5/CoreCLR friendly in the coming months - possibly breaking up packages from core logging and the web views (with an easy dependency, of course - still a one-package add).

**Comment by NickCraver** [comment]
Tagging is now started on the master branch and the new build system for packages will enforce it going forward, thanks for this!
