### ISSUE TITLE
Prevent Certain Form Elements From Being Logged

### ISSUE THREAD

**Issue by mmillican** [NickCraver/StackExchange.Exceptional#64]
I know it is possible to ignore exceptions by regex or by system type, however, I am wondering if it's possible to ignore certain form data (eg, passwords) from being logged with an exception.  I would like to be able to log possible exceptions from items that deal with sensitive data, but obviously don't want that stored in plain text.

**Comment by NickCraver** [comment]
Yep, this is supported. You can do this via the `LogFilter`, here's an example from our OpenID Provider:

```XML
  <Exceptional applicationName="Open ID">
    <LogFilters>
      <Form>
        <add name="password" replaceWith="********" />
        <add name="password2" replaceWith="********" />
      </Form>
    </LogFilters>
    <ErrorStore type="Memory" />
  </Exceptional>
```

**Comment by mmillican** [comment]
Should have known :).  I also see it in the example now.

Thanks @NickCraver
