### ISSUE TITLE
Async-friendly format for stack traces and exceptions

### ISSUE THREAD

**Issue by yuzukwok** [NickCraver/StackExchange.Exceptional#68]
https://github.com/aelij/AsyncFriendlyStackTrace

**Comment by NickCraver** [comment]
I agree this needs doing - I'll make sure some form on it lands in V2.

**Comment by NickCraver** [comment]
I've got a first pass of this into the V2 branch. Here's what a stack trace looks like today vs. what the new prettified version looks like:
<img width="1000" alt="screen shot 2017-07-16 at 19 24 46" src="https://user-images.githubusercontent.com/454813/28252778-2467895c-6a68-11e7-9661-6d27dcae447f.png">
...and the new stuff:
<img width="1001" alt="screen shot 2017-07-16 at 19 24 12" src="https://user-images.githubusercontent.com/454813/28252780-2f216570-6a68-11e7-85f5-6cf168f2718f.png">
I'll be adding a button to "show all" underneath that view in the next pass. I hope this is an improvement over the plain stack trace, please give me your thoughts!

**Comment by NickCraver** [comment]
Closing this out since we're live in V2 with it, I'll be merging to master when ASP.NET Core support is in and ready for alpha.
