### ISSUE TITLE
Error not found

### ISSUE THREAD

**Issue by mmillican** [NickCraver/StackExchange.Exceptional#71]
Using the following configuration (same as other apps), Opserver is saying "Error not found" when you hover over it or click on it.
![2016-04-ct54z](https://cloud.githubusercontent.com/assets/810260/14726327/0f87aac4-07e7-11e6-9e04-6ad18abe0dbd.png)

    <system.webServer>
    ....
        <modules runAllManagedModulesForAllRequests="true">
            <add name="ErrorLog" type="StackExchange.Exceptional.ExceptionalModule,               StackExchange.Exceptional" />
     </modules>
    ....
    </system.webServer>

    <Exceptional applicationName="Sales Portal">
        <LogFilters>
            <Form>
                <add name="password" replaceWith="******" />
                <add name="__RequestVerificationToken" replaceWith="******" />
            </Form>
            <Cookies>
                <add name="Marcus" replaceWith="******" />
            </Cookies>
        </LogFilters>
        <ErrorStore type="SQL" connectionStringName="LoggingDb" />
    </Exceptional>

I've had this issue with one other app, but the issue seems to have resolved itself.  Any ideas?

**Comment by NickCraver** [comment]
Have you tried the `overhaul` branch? The caching semantics are drastically improved on some race situations. If this is consistently reproducible, what does your Opserver config look like?

**Comment by mmillican** [comment]
@NickCraver I have not yet.  I can try that this weekend.  

Would it matter at all that the ones I noticed recently are from my local machine and not a server?  I wouldn't think so, but curious.  I don't remember if this was the case before or not.

**Comment by mmillican** [comment]
@NickCraver Looks like deploying the `opserver/overhaul` branch did the trick, for now at least.  I'll let you know if I see otherwise.

PS - Overhaul looks awesome!
