### ISSUE TITLE
Does this library work with WebForms sites?

### ISSUE THREAD

**Issue by bplus** [NickCraver/StackExchange.Exceptional#72]
Is this library only for MVC, or should it catch exceptions for WebForms sites?

**Comment by CptRobby** [comment]
It works for reporting errors in WebForms just fine. It can also be used to report errors in desktop applications. It's pretty agnostic to the environment it is running in as long as it can connect to the store and there's some method for handing it the exceptions that are thrown.

As for using the HttpHandler to show the errors on a web page, I think you just need to have your website running in a .Net 4 pool (but I might be wrong about that). But even if you can't use that particular part of it from within your website, you could still just create another website and it'll work just fine as long as it has the same connection string.

**Comment by NickCraver** [comment]
@CptRobby covered it here - closing out to cleanup.
