### ISSUE TITLE
Not catching Soap/WebAPI exceptions

### ISSUE THREAD

**Issue by itssimple** [NickCraver/StackExchange.Exceptional#74]
It seems that Exceptional is not catching the exceptions thrown by WebAPI-controllers or Soap Webservices.

Callstack for WebAPI-exception is like this:

`at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary'2 arguments, CancellationToken cancellationToken)
`
I have no current example of soap-webservice (but they aren't that important any longer)

**Comment by AlexSikilinda** [comment]
@itssimple, try adding `runAllManagedModulesForAllRequests="true"` to `web.config` when you add error handler:
```
<modules runAllManagedModulesForAllRequests="true">
    <add name="ErrorLog" type="StackExchange.Exceptional.ExceptionalModule, StackExchange.Exceptional" />
</modules>
```

**Comment by NickCraver** [comment]
What @AlexSikilinda suggest is correct - let me know if this doesn't resolve and I'll reopen :)
