### ISSUE TITLE
Add netstandard & ASP.NET Core support

### ISSUE THREAD

**Issue by NickCraver** [NickCraver/StackExchange.Exceptional#80]
V2 needs ASP.NET Core and netstandard support included. This will follow the library split patterns of MiniProfiler, but there's a blocker in play. A critical component of Exceptional is `AppDomain.UnhandledException`, but unfortunately this isn't coming back until `netstandard2.0`.

That issue is resolved here: https://github.com/dotnet/corefx/issues/6398, just waiting for that release to get going. Now that I've figured out patterns and beat the crap out of the build system with MiniProfiler, actually porting StackExchange.Exceptional won't be a huge task.

**Comment by mmillican** [comment]
@NickCraver Do you have any thoughts on the mail sending for Exceptional as it relates to the port?  Using jstedfast/MailKit perhaps?

**Comment by nickalbrecht** [comment]
The AppDomain's exception handler will be nice to have once it's out. Any plans to have an interim build that will support ASP.NET Core (regardless if the underlying framework is full .NET  or .NET Core) and just register it as a Middleware handler, similar to the `UseDeveloperExceptionPage()` implementation?

**Comment by NickCraver** [comment]
`master` has a first pass of ASP.NET Core support, lots of tweaking and such to do, but samples are up. I'm looking at the built-in error page and thinking yeah, we should have an option to have it render on the throw (instead of just re-throwing), that's next up.

**Comment by NickCraver** [comment]
Here's an example of the current functionality in master:
```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseExceptional(settings => 
    {
        settings.ApplicationName = "Samples.AspNetCore";
        settings.UseExceptionalPageOnThrow = env.IsDevelopment();
    });
}
```
And here's the result:
![screen shot 2017-08-09 at 22 05 15](https://user-images.githubusercontent.com/454813/29245249-48c30c28-7fa2-11e7-95f6-0a61a9e5c86d.png)
![screen shot 2017-08-09 at 22 04 57](https://user-images.githubusercontent.com/454813/29245252-5cd12fd8-7fa2-11e7-8745-93ce9ef7aabc.png)

You can: register it as a middleware (always logging and optionally handling the throw page like above) and you can just `new Exception("blah").Log(Context)` anywhere (or without context with `LogWithoutContext()`).

Closing this out to cleanup, we'll have settings in soon to round out support - alpha around the corner.
