### ISSUE TITLE
Any plans to add MongoDB store?

### ISSUE THREAD

**Issue by stevencasey** [NickCraver/StackExchange.Exceptional#9]
Just checking that no-one else is, before I go off and implement it.

Thanks

**Comment by Rabosa616** [comment]
Hi Nick,
Any plans for that?

**Comment by MattJeanes** [comment]
Hi guys, I've just spend an hour or two writing up a MongoDB error store for the AspNetCore preview version - I'll see if I can turn it into a PR but seems to work fine!

Here's a gist of it if you want to take a look (or just copy paste it, but having it officially would be nice): https://gist.github.com/MattJeanes/46e7bfef1b3d962430abe14ef4a09bca

![image](https://user-images.githubusercontent.com/2363642/48813216-d7861500-ed2d-11e8-9d84-8067573d281b.png)

![2018-11-21_01-38-48](https://user-images.githubusercontent.com/2363642/48813325-43687d80-ed2e-11e8-86ea-716c5de564fa.gif)

**Comment by MattJeanes** [comment]
Have created a PR to resolve this: #153
