### ISSUE TITLE
ErrorStore.Setup doesn't set Settings.Current.ApplicationName

### ISSUE THREAD

**Issue by stijnherreman** [NickCraver/StackExchange.Exceptional#99]
Version: 2.0.0-alpha-129

`ErrorStore.Setup("MyApplication", new SQLErrorStore(exceptionalConnectionString));` doesn't set `Settings.Current.ApplicationName`, so logging an exception fails due to `ApplicationName` being null.

Is this scenario still supported or does the documentation need updating?

**Comment by NickCraver** [comment]
Fixed in #107, the settings craziness needs some love so this may shift some more, but will work in the next alpha.
